// @generated
// This file is @generated by prost-build.
// =============================================
// LAYER 1: Settlement Extraction
// =============================================

/// All x402 settlements detected in a block
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settlements {
    #[prost(message, repeated, tag="1")]
    pub settlements: ::prost::alloc::vec::Vec<Settlement>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(message, optional, tag="3")]
    pub block_timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// A single x402 payment settlement
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settlement {
    /// tx_hash-log_index
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub log_index: u32,
    #[prost(uint64, tag="4")]
    pub block_number: u64,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Payment details
    ///
    /// Who paid (token sender)
    #[prost(string, tag="6")]
    pub payer: ::prost::alloc::string::String,
    /// Resource server (payTo)
    #[prost(string, tag="7")]
    pub recipient: ::prost::alloc::string::String,
    /// Token address (e.g. USDC)
    #[prost(string, tag="8")]
    pub token: ::prost::alloc::string::String,
    /// Payment amount (atomic units)
    #[prost(string, tag="9")]
    pub amount: ::prost::alloc::string::String,
    /// Settlement classification
    ///
    /// "settled", "settled_with_permit", "eip3009"
    #[prost(string, tag="10")]
    pub settlement_type: ::prost::alloc::string::String,
    /// Facilitator info (who submitted tx and paid gas)
    ///
    /// msg.sender / tx.from
    #[prost(string, tag="11")]
    pub facilitator: ::prost::alloc::string::String,
    /// Gas consumed by the transaction
    #[prost(string, tag="12")]
    pub gas_used: ::prost::alloc::string::String,
    /// Effective gas price (wei)
    #[prost(string, tag="13")]
    pub gas_price: ::prost::alloc::string::String,
    /// Raw proxy event data (for future decoding)
    ///
    /// Topic\[0\] of the proxy event
    #[prost(string, tag="14")]
    pub proxy_event_sig: ::prost::alloc::string::String,
    /// Hex-encoded event data
    #[prost(string, tag="15")]
    pub proxy_event_data: ::prost::alloc::string::String,
}
/// USDC transfer events correlated with x402 settlements
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentTransfers {
    #[prost(message, repeated, tag="1")]
    pub transfers: ::prost::alloc::vec::Vec<PaymentTransfer>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentTransfer {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub log_index: u32,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(message, optional, tag="4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="5")]
    pub from_address: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub to_address: ::prost::alloc::string::String,
    /// USDC amount (6 decimals)
    #[prost(string, tag="7")]
    pub amount: ::prost::alloc::string::String,
    /// Token contract address
    #[prost(string, tag="8")]
    pub token: ::prost::alloc::string::String,
    /// Transaction sender
    #[prost(string, tag="9")]
    pub facilitator: ::prost::alloc::string::String,
    /// Tx also has x402 proxy events
    #[prost(bool, tag="10")]
    pub is_x402_related: bool,
}
// =============================================
// LAYER 3: Analytics
// =============================================

/// Aggregated payer statistics
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayerStats {
    #[prost(message, repeated, tag="1")]
    pub stats: ::prost::alloc::vec::Vec<PayerStat>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayerStat {
    #[prost(string, tag="1")]
    pub payer_address: ::prost::alloc::string::String,
    /// Total USDC spent
    #[prost(string, tag="2")]
    pub total_spent: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub total_payments: u64,
    #[prost(message, optional, tag="4")]
    pub first_payment_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="5")]
    pub last_payment_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Aggregated recipient (resource server) statistics
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecipientStats {
    #[prost(message, repeated, tag="1")]
    pub stats: ::prost::alloc::vec::Vec<RecipientStat>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecipientStat {
    #[prost(string, tag="1")]
    pub recipient_address: ::prost::alloc::string::String,
    /// Total USDC received
    #[prost(string, tag="2")]
    pub total_received: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub total_payments: u64,
    #[prost(message, optional, tag="4")]
    pub first_payment_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="5")]
    pub last_payment_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Facilitator gas economics
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FacilitatorStats {
    #[prost(message, repeated, tag="1")]
    pub stats: ::prost::alloc::vec::Vec<FacilitatorStat>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FacilitatorStat {
    #[prost(string, tag="1")]
    pub facilitator_address: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub total_settlements: u64,
    /// Total USDC volume processed
    #[prost(string, tag="3")]
    pub total_volume_settled: ::prost::alloc::string::String,
    /// Total gas cost in wei
    #[prost(string, tag="4")]
    pub total_gas_spent: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub first_settlement_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="6")]
    pub last_settlement_at: ::core::option::Option<::prost_types::Timestamp>,
}
// @@protoc_insertion_point(module)
